name: "PNPM setup"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 8

    - name: Use Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: 21
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
