name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ci-setup

      - name: ESLint
        run: pnpm lint

  format:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ci-setup

      - name: Prettier
        run: pnpm format:check
