name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  linting:
    name: 🕵 Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci-setup

      - name: ESLint
        run: pnpm lint

  format:
    name: 💅 Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci-setup

      - name: Prettier
        run: pnpm format:check

  build:
    name: 💣 Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/ci-setup

      - name: Build
        run: pnpm build
